//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiYalex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
    
        public int id_cliente { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string licencia { get; set; }
        public string dui { get; set; }
        public string estado { get; set; }
        public string contrasena { get; set; }
        public string rol { get; set; }
    }
}
